export const pokemonAPI = "https://pokeapi.co/api/v2";
export const pokemonsRoute = `${pokemonAPI}/pokemon?limit=5000`;
export const pokemonRoute = `${pokemonAPI}/pokemon`;
export const pokemonSpeciesRoute = `${pokemonAPI}/pokemon-species`;
export const pokemonsEvoChain = `${pokemonAPI}/evolution-chain`;

export const navLinks = [
  {
    id: "Pokedex",
    title: "Pokedex",
  },
  {
    id: "Mylist",
    title: "My list",
  },
];

const styles = {
  paddingX: "sm:px-16 px-6",
  paddingY: "sm:py-16 py-6",
  padding: "sm:px-16 px-6 sm:py-16 py-10",

  heroHeadText:
    "font-black text-white lg:text-[80px] sm:text-[60px] xs:text-[50px] text-[40px] lg:leading-[98px] mt-2",
  heroSubText:
    "text-[#f4dc26] font-medium lg:text-[30px] sm:text-[26px] xs:text-[20px] text-[16px] lg:leading-[40px]",

  sectionHeadText:
    "text-white font-black md:text-[60px] sm:text-[50px] xs:text-[40px] text-[30px]",
  sectionSubText:
    "sm:text-[32px] text-[14px] text-secondary uppercase tracking-wider",
};

export const pokeType = [
  { name: "normal", color: "graylight" },
  { name: "fighting", color: "orange" },
  { name: "flying", color: "lightblue" },
  { name: "poison", color: "purple" },
  { name: "ground", color: "brown" },
  { name: "rock", color: "goldenrod" },
  { name: "bug", color: "green" },
  { name: "ghost", color: "purple" },
  { name: "steel", color: "slate" },
  { name: "fire", color: "red" },
  { name: "water", color: "blue" },
  { name: "grass", color: "lightgreen" },
  { name: "electric", color: "yellow" },
  { name: "psychic", color: "pink" },
  { name: "ice", color: "cerulean" },
  { name: "dragon", color: "lightRed" },
  { name: "dark", color: "gray" },
  { name: "fairy", color: "lightpink" },
];

export const colorVariants = {
  blue: "bg-blue-600 text-white",
  red: "bg-red-500",
  yellow: "bg-yellow-300",
  green: "bg-green-600",
  purple: "bg-purple-600",
  gray: "bg-neutral-900",
  slate: "bg-slate-500",
  cerulean: "bg-sky-300",
  pink: "bg-pink-500",
  orange: "bg-orange-500",
  brown: "bg-amber-800",
  lightblue: "bg-blue-300",
  lightgreen: "bg-green-400",
  lightpink: "bg-pink-300",
  lightRed: "bg-cyan-500",
  goldenrod: "bg-yellow-800",
  graylight: "bg-gray-400",
};

export const nameStat = [
  "HP",
  "Attack",
  "Defense",
  "Special Attack",
  "Special Defense",
  "Speed",
];

export const pokemon = new Array(
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "Nidoran",
  "Nidorina",
  "Nidoqueen",
  "Nidoran",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr. Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew"
);

export { styles };
